<?php
/**
 * Steam Emulator Test Panel - Configuration
 * Generated by installer on 2026-01-21 03:46:29
 */

// Error reporting (disable in production)
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Session configuration
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// MySQL Database configuration
define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'test_api');
define('DB_USER', '');
define('DB_PASS', '');
define('DB_CHARSET', 'utf8mb4');

// Legacy path (not used with MySQL, kept for compatibility)
define('DB_PATH', __DIR__ . '/data/test_panel.db');

// Authentication credentials (legacy - now stored in database)
define('AUTH_USERS', []);

// Panel settings
define('PANEL_NAME', 'Steam Emulator Test Panel');
define('ITEMS_PER_PAGE', 25);

// GitHub Integration - for tracking commit revisions
define('GITHUB_OWNER', '');
define('GITHUB_REPO', '');
define('GITHUB_TOKEN', '');

// Status colors for consistency - OldSteam Theme
define('STATUS_COLORS', [
    'Working' => '#7ea64b',      // FullGreen
    'Semi-working' => '#c4b550', // Maize/Yellow
    'Not working' => '#c45050',  // Red
    'N/A' => '#808080',          // Gray
    '' => '#808080'
]);

// Theme colors - OldSteam Theme
define('THEME', [
    'bg_dark' => '#3e4637',      // DarkGreenBG
    'bg_card' => '#4c5844',      // GreenBG
    'bg_accent' => '#5a6a50',    // LightGreenBG
    'primary' => '#c4b550',      // Maize/Yellow
    'primary_dark' => '#91863c', // MaizeBG
    'full_green' => '#7ea64b',   // FullGreen
    'text' => '#eff6ee',         // Off-white
    'text_muted' => '#a0aa95',   // Label
    'border' => '#282e22',       // BorderDark
    'border_bright' => '#808080' // BorderBright
]);

// Timezone
date_default_timezone_set('America/Chicago');
