<?php
/**
 * Submit report page
 */

require_once __DIR__ . '/../includes/header.php';
require_once __DIR__ . '/../includes/db.php';

$db = Database::getInstance();

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $error = null;
    $success = false;

    // Check if file was uploaded
    if (isset($_FILES['report_file']) && $_FILES['report_file']['error'] === UPLOAD_ERR_OK) {
        $tmpFile = $_FILES['report_file']['tmp_name'];
        $content = file_get_contents($tmpFile);
        $json = json_decode($content, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            $error = 'Invalid JSON file: ' . json_last_error_msg();
        } else {
            // Parse the test tool JSON format - returns array of all versions
            $allReports = parseTestToolJson($json);

            if (!$allReports || empty($allReports)) {
                $error = 'Invalid report format. Expected test tool JSON structure.';
            } else {
                $insertedReports = [];
                $failedReports = [];

                // Insert ALL reports (one per version)
                foreach ($allReports as $parsed) {
                    $reportId = $db->insertReport(
                        $parsed['tester'],
                        $parsed['commit_hash'],
                        $parsed['test_type'],
                        $parsed['client_version'],
                        $content,
                        $parsed['test_duration'] ?? null
                    );

                    if ($reportId) {
                        // Insert test results
                        foreach ($parsed['results'] as $testKey => $result) {
                            $db->insertTestResult(
                                $reportId,
                                $testKey,
                                $result['status'],
                                cleanNotes($result['notes'])
                            );
                        }
                        $insertedReports[] = [
                            'id' => $reportId,
                            'version' => $parsed['client_version']
                        ];
                    } else {
                        $failedReports[] = $parsed['client_version'];
                    }
                }

                if (!empty($insertedReports)) {
                    $success = true;
                    $count = count($insertedReports);
                    if ($count === 1) {
                        setFlash('success', 'Report submitted successfully!');
                        header('Location: ?page=report_detail&id=' . $insertedReports[0]['id']);
                    } else {
                        setFlash('success', "{$count} reports submitted successfully!");
                        header('Location: ?page=reports');
                    }
                    exit;
                } else {
                    $error = 'Failed to save reports to database.';
                }
            }
        }
    } elseif (isset($_FILES['report_file'])) {
        $uploadErrors = [
            UPLOAD_ERR_INI_SIZE => 'File exceeds upload_max_filesize',
            UPLOAD_ERR_FORM_SIZE => 'File exceeds MAX_FILE_SIZE',
            UPLOAD_ERR_PARTIAL => 'File was only partially uploaded',
            UPLOAD_ERR_NO_FILE => 'No file was uploaded',
            UPLOAD_ERR_NO_TMP_DIR => 'Missing temp folder',
            UPLOAD_ERR_CANT_WRITE => 'Failed to write file to disk',
            UPLOAD_ERR_EXTENSION => 'Upload blocked by extension',
        ];
        $error = $uploadErrors[$_FILES['report_file']['error']] ?? 'Unknown upload error';
    } else {
        $error = 'No file uploaded.';
    }

    if ($error) {
        setFlash('error', $error);
    }
}

// Get user's API key from session
$user = getCurrentUser();
$apiKey = $user['api_key'] ?? 'Not available';
?>

<h1 class="page-title">Submit Report</h1>

<div class="two-col">
    <!-- Upload Form -->
    <div class="card">
        <h3 class="card-title">Upload JSON Report</h3>
        <p style="color: var(--text-muted); margin-bottom: 20px;">
            Upload a <code>session_results.json</code> file generated by the test tool.
        </p>

        <form method="POST" enctype="multipart/form-data" id="uploadForm">
            <div class="file-drop-zone" id="dropZone">
                <div class="drop-zone-content">
                    <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="color: var(--primary); margin-bottom: 10px;">
                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                        <polyline points="17,8 12,3 7,8"></polyline>
                        <line x1="12" y1="3" x2="12" y2="15"></line>
                    </svg>
                    <p class="drop-zone-text">Drag and drop your JSON file here</p>
                    <p style="color: var(--text-muted); font-size: 13px; margin-bottom: 15px;">or</p>
                    <button type="button" class="btn btn-secondary" id="browseBtn">Browse Files</button>
                    <input type="file" name="report_file" id="fileInput" accept=".json,application/json" style="display: none;">
                </div>
                <div class="file-selected" id="fileSelected" style="display: none;">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="color: var(--full-green);">
                        <path d="M14,2 L6,2 C4.9,2 4,2.9 4,4 L4,20 C4,21.1 4.9,22 6,22 L18,22 C19.1,22 20,21.1 20,20 L20,8 L14,2 Z"></path>
                        <polyline points="14,2 14,8 20,8"></polyline>
                    </svg>
                    <span id="fileName" style="margin-left: 10px; color: var(--text);"></span>
                    <button type="button" class="btn-remove" id="removeFile" title="Remove file">&times;</button>
                </div>
            </div>
            <button type="submit" class="btn" id="submitBtn" style="margin-top: 15px; width: 100%;" disabled>Upload Report</button>
        </form>

        <div style="margin-top: 20px;">
            <h4 style="font-size: 14px; margin-bottom: 10px;">Expected Format</h4>
            <pre style="background: var(--bg-dark); padding: 15px; border-radius: 6px; font-size: 12px; overflow-x: auto; color: var(--text-muted);">{
  "metadata": {
    "tester_name": "John Doe",
    "commit_hash": "abc123",
    "test_type": "WAN"
  },
  "tests": {
    "Version Name": {
      "1": { "status": "Working", "notes": "" },
      "2": { "status": "Semi-working", "notes": "Some issues" },
      ...
    }
  }
}</pre>
        </div>
    </div>

    <!-- API Documentation -->
    <div class="card">
        <h3 class="card-title">API Submission</h3>
        <p style="color: var(--text-muted); margin-bottom: 20px;">
            You can also submit reports programmatically using the API.
        </p>

        <div class="form-group">
            <label>Your API Key</label>
            <input type="text" value="<?= e($apiKey) ?>" readonly onclick="this.select();" style="font-family: monospace;">
        </div>

        <h4 style="font-size: 14px; margin: 20px 0 10px;">Endpoint</h4>
        <code style="background: var(--bg-dark); padding: 8px 12px; border-radius: 4px; display: block;">
            POST <?= e(getBaseUrl()) ?>/api/submit.php
        </code>

        <h4 style="font-size: 14px; margin: 20px 0 10px;">Headers</h4>
        <pre style="background: var(--bg-dark); padding: 15px; border-radius: 6px; font-size: 12px; overflow-x: auto; color: var(--text-muted);">Content-Type: application/json
X-API-Key: YOUR_API_KEY</pre>

        <h4 style="font-size: 14px; margin: 20px 0 10px;">Python Script</h4>
        <p style="color: var(--text-muted); margin-bottom: 10px;">
            Use the included Python script for easy submission:
        </p>
        <pre style="background: var(--bg-dark); padding: 15px; border-radius: 6px; font-size: 12px; overflow-x: auto; color: var(--text-muted);">python submit_report.py \
  --url <?= e(getBaseUrl()) ?>/api/submit.php \
  --api-key YOUR_API_KEY \
  --file session_results.json</pre>

        <h4 style="font-size: 14px; margin: 20px 0 10px;">cURL Example</h4>
        <pre style="background: var(--bg-dark); padding: 15px; border-radius: 6px; font-size: 12px; overflow-x: auto; color: var(--text-muted);">curl -X POST <?= e(getBaseUrl()) ?>/api/submit.php \
  -H "Content-Type: application/json" \
  -H "X-API-Key: YOUR_API_KEY" \
  -d @session_results.json</pre>
    </div>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
